Nodejs setup in typescript:
- https://www.digitalocean.com/community/tutorials/setting-up-a-node-project-with-typescript
Typescript nodemon:
- https://futurestud.io/tutorials/typescript-use-nodemon-to-restart-your-server-on-changes
Error Handling:
- https://www.toptal.com/nodejs/node-js-error-Handling
- https://sematext.com/blog/node-js-error-handling/
Http Logging:
- https://codesource.io/creating-a-logging-middleware-in-expressjs/

Websites:
- https://medium.com/@sundar.sat84/bip39-mnemonic-generation-with-detailed-explanation-84abde9da4c1
